name: Integration tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v1
        with:
          php-version: '7.3'
          extensions: intl
      - run: composer install
      - run: vendor/bin/php-cs-fixer fix --diff --diff-format=udiff --using-cache=no --dry-run src
      - run: vendor/bin/php-cs-fixer fix --diff --diff-format=udiff --using-cache=no --dry-run tests
      - run: vendor/bin/phpunit
